network:
  version: 2
  renderer: networkd
  ethernets:
     enp1s0:
      dhcp4: false
      addresses:
      - 192.168.122.221/24
      routes:
      - to: default
        via: 192.168.122.1
      nameservers:
       addresses: [8.8.8.8,8.8.4.4]
