---
# tasks file for .

- name: Install a list of packages
  become: true
  apt:
    update_cache: yes
    pkg:
      - git

- name: Config git
  become: true
  git_config:
    name: safe.directory
    scope: global
    value: /opt/devstack

- name: Dowmload source code
  become: true
  git:
   repo: https://github.com/openstack-dev/devstack.git
   dest: /opt/devstack

- name: Change script to executable mode
  become: true
  file:
   path: /opt/devstack/tools/create-stack-user.sh
   mode: u+x,g+x,o+x

- name: Create users and group for stack
  become: true
  environment:
    HOST_IP: "{{ansible_default_ipv4.address}}"
  shell: /opt/devstack/tools/create-stack-user.sh

- name: Change user and group path
  become: true
  file:
    path: /opt/devstack
    recurse: yes
    owner: stack
    group: stack

- name: Create local.conf
  become: true
  template:
    src: local.conf.j2
    dest: /opt/devstack/local.conf
    owner: stack
    group: stack

- name: Change user and group path
  become: true
  file:
    path: "{{item}}"
    recurse: yes
    owner: stack
    group: stack
  with_items:
     - /opt/stack/
     - /opt/stack/logs/

- name: Execute stacking
  become: true
  environment:
    FORCE: "yes"
  shell: su - stack -c /opt/devstack/stack.sh
